ministryofjustice/hmpps-nomis-mapping-service

build.gradle.kts, src/test/kotlin/uk/gov/justice/digital/hmpps/nomisvisitsmappingservice/resource/OpenApiDocsTest.kt
=> Sdi 157 upgrade

helm_deploy/hmpps-nomis-mapping-service/values.yaml
=> SDI-396 Change domain name and namespace

src/main/kotlin/uk/gov/justice/digital/hmpps/nomisvisitsmappingservice/data/ActivityMappingDto.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/nomisvisitsmappingservice/jpa/ActivityMapping.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/nomisvisitsmappingservice/jpa/repository/ActivityMappingRepository.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/nomisvisitsmappingservice/resource/ActivityMappingResource.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/nomisvisitsmappingservice/resource/IncentiveMappingResource.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/nomisvisitsmappingservice/service/ActivityMappingService.kt, src/main/resources/db/migration/V1_12__activity.sql, src/test/kotlin/uk/gov/justice/digital/hmpps/nomisvisitsmappingservice/helper/builders/ActivityRepository.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/nomisvisitsmappingservice/jpa/repository/ActivityMappingRepositoryTest.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/nomisvisitsmappingservice/resource/ActivityMappingResourceIntTest.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/nomisvisitsmappingservice/resource/IncentiveMappingResourceIntTest.kt
=> SDI-505 Handle activities.activity.created event

build.gradle.kts, src/main/kotlin/uk/gov/justice/digital/hmpps/nomisvisitsmappingservice/resource/AppointmentMappingResource.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/nomisvisitsmappingservice/service/AppointmentMappingService.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/nomisvisitsmappingservice/resource/AppointmentMappingResourceIntTest.kt
=> SDIT-800 Link up the activities api migrate appointments endpoint

src/main/kotlin/uk/gov/justice/digital/hmpps/nomisvisitsmappingservice/config/NomisMappingServiceExceptionHandler.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/nomisvisitsmappingservice/resource/ActivityMappingResource.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/nomisvisitsmappingservice/resource/AdjudicationsMappingResource.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/nomisvisitsmappingservice/resource/AppointmentMappingResource.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/nomisvisitsmappingservice/resource/IncentiveMappingResource.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/nomisvisitsmappingservice/resource/SentencingMappingResource.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/nomisvisitsmappingservice/resource/VisitMappingResource.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/nomisvisitsmappingservice/jpa/repository/IncentiveMappingRepositoryTest.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/nomisvisitsmappingservice/resource/ActivityMappingResourceIntTest.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/nomisvisitsmappingservice/resource/AdjudicationMappingResourceIntTest.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/nomisvisitsmappingservice/resource/AppointmentMappingResourceIntTest.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/nomisvisitsmappingservice/resource/IncentiveMappingResourceIntTest.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/nomisvisitsmappingservice/resource/SentencingAdjustmentMappingResourceIntTest.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/nomisvisitsmappingservice/resource/VisitMappingResourceIntTest.kt
=> SDIT-936 Duplicate mapping not detected

src/main/kotlin/uk/gov/justice/digital/hmpps/nomisvisitsmappingservice/data/AdjudicationMappingDto.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/nomisvisitsmappingservice/jpa/AdjudicationMapping.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/nomisvisitsmappingservice/jpa/repository/AdjudicationMappingRepository.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/nomisvisitsmappingservice/resource/AdjudicationsMappingResource.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/nomisvisitsmappingservice/service/AdjudicationMappingService.kt, src/main/resources/db/migration/V1_24__adjudication.sql, src/test/kotlin/uk/gov/justice/digital/hmpps/nomisvisitsmappingservice/resource/AdjudicationMappingResourceIntTest.kt
Each adjudication can have 1 or more charge, in DPS this will map to each adjudication identified by a charge number that we expect to be format of "adjudication/chargeSequence"
So this adds the DPS key to mapping and expands NOMIS id to include charge sequence
=> SDI-941 Added charge sequence to mapping and the expected DPS charge number

src/main/kotlin/uk/gov/justice/digital/hmpps/nomisvisitsmappingservice/data/AdjudicationPunishmentMappingDto.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/nomisvisitsmappingservice/jpa/repository/AdjudicationPunishmentMappingRepository.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/nomisvisitsmappingservice/resource/PunishmentsMappingResource.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/nomisvisitsmappingservice/service/AdjudicationMappingService.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/nomisvisitsmappingservice/resource/PunishmentsMappingResourceIntTest.kt
DPS updates punishments in a batch, some can be created and some can be deleted
=> SDI-1162 endpoint that can update punishment mappings

src/main/kotlin/uk/gov/justice/digital/hmpps/nomisvisitsmappingservice/data/LocationMappingDto.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/nomisvisitsmappingservice/jpa/LocationMapping.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/nomisvisitsmappingservice/jpa/repository/LocationMappingRepository.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/nomisvisitsmappingservice/resource/LocationMappingResource.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/nomisvisitsmappingservice/service/AppointmentMappingService.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/nomisvisitsmappingservice/service/IncentiveMappingService.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/nomisvisitsmappingservice/service/IncidentMappingService.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/nomisvisitsmappingservice/service/LocationMappingService.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/nomisvisitsmappingservice/service/NonAssociationMappingService.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/nomisvisitsmappingservice/service/SentencingMappingService.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/nomisvisitsmappingservice/service/VisitMappingService.kt, src/main/resources/db/migration/V1_34__location.sql, src/test/kotlin/uk/gov/justice/digital/hmpps/nomisvisitsmappingservice/helper/builders/LocationRepository.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/nomisvisitsmappingservice/resource/AppointmentMappingResourceIntTest.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/nomisvisitsmappingservice/resource/IncentiveMappingResourceIntTest.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/nomisvisitsmappingservice/resource/IncidentMappingResourceIntTest.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/nomisvisitsmappingservice/resource/LocationMappingResourceIntTest.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/nomisvisitsmappingservice/resource/NonAssociationMappingResourceIntTest.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/nomisvisitsmappingservice/resource/SentencingAdjustmentMappingResourceIntTest.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/nomisvisitsmappingservice/resource/VisitMappingResourceIntTest.kt
=> SDIT-1482 Mapping endpoints for Locations

build.gradle.kts, helm_deploy/values-dev.yaml, helm_deploy/values-preprod.yaml, helm_deploy/values-prod.yaml, src/main/resources/application-dev.yml, src/main/resources/application.yml, src/test/resources/application-test.yml
Straightforward as this lib doesn't call out, so no changes tot web clients or health checks. But a good test that the kotlin library isn't intrusive.
=> SDIT-1336 Latest hmpps-kotlin-spring-boot-starter lib

src/main/kotlin/uk/gov/justice/digital/hmpps/nomisvisitsmappingservice/jpa/repository/SentenceAdjustmentMappingRepository.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/nomisvisitsmappingservice/resource/SentencingMappingResource.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/nomisvisitsmappingservice/service/SentencingMappingService.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/nomisvisitsmappingservice/resource/SentencingAdjustmentMappingResourceIntTest.kt
Get all paged - essentially so we know if db is empty
=> SDIT-1574 Add endpoint to retrieve alert mappings by DPS id

src/main/kotlin/uk/gov/justice/digital/hmpps/nomisvisitsmappingservice/alerts/AlertMapping.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/nomisvisitsmappingservice/alerts/AlertMappingDto.kt, src/main/resources/db/migration/V1_43__alert_prisoner_number-notnull.sql, src/test/kotlin/uk/gov/justice/digital/hmpps/nomisvisitsmappingservice/alerts/AlertMappingResourceIntTest.kt
No data in any environment should be null now so implement this change
=> SDIT-1658 Make offenderNo non-nullable

src/main/kotlin/uk/gov/justice/digital/hmpps/nomisvisitsmappingservice/alerts/AlertMappingDto.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/nomisvisitsmappingservice/alerts/AlertMappingService.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/nomisvisitsmappingservice/alerts/AlertsMappingResource.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/nomisvisitsmappingservice/alerts/AlertMappingResourceIntTest.kt
Update the nomis booking id so that an alert can transfer to a new booking for that prisoner
=> SDIT-1546 Update alert mapping endpoint

src/main/kotlin/uk/gov/justice/digital/hmpps/nomisvisitsmappingservice/alerts/AlertMappingDto.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/nomisvisitsmappingservice/alerts/AlertMappingService.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/nomisvisitsmappingservice/alerts/AlertsMappingRepository.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/nomisvisitsmappingservice/alerts/AlertsMappingResource.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/nomisvisitsmappingservice/alerts/AlertMappingResourceIntTest.kt
* POST /mapping/alerts/batch  - require to created mappings after a prisoner merge
* GET /mapping/alerts/{offenderNo}/all - utility for diagnostics
* GET /mapping/alerts - utility for diagnostics
=> SDIT-1568 Various alerts mapping endpoints 

src/main/kotlin/uk/gov/justice/digital/hmpps/nomisvisitsmappingservice/alerts/AlertMappingService.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/nomisvisitsmappingservice/alerts/AlertsMappingResource.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/nomisvisitsmappingservice/alerts/AlertMappingResourceIntTest.kt
Similar to the POST equivalent except does not write a prisoner mapping record
=> SDIT-1859 Replace Alert mappings new endpoint

src/main/kotlin/uk/gov/justice/digital/hmpps/nomisvisitsmappingservice/casenotes/CaseNoteMappingDto.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/nomisvisitsmappingservice/casenotes/CaseNoteMappingService.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/nomisvisitsmappingservice/casenotes/CaseNotesMappingResource.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/nomisvisitsmappingservice/casenotes/CaseNoteMappingResourceIntTest.kt
Add migration-id and count endpoints
=> SDIT-1800 Create casenotes mapping endpoints

src/main/kotlin/uk/gov/justice/digital/hmpps/nomisvisitsmappingservice/api/PublicApiResource.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/nomisvisitsmappingservice/api/PublicApiResourceIntTest.kt
API to be used by DPS service that need to migrate their own services from NOMIS stored data to DPS data.
=> SDIT-2005 Add public API for location mapping

src/main/kotlin/uk/gov/justice/digital/hmpps/nomisvisitsmappingservice/contactperson/ContactPersonMappingResource.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/nomisvisitsmappingservice/contactperson/ContactPersonService.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/nomisvisitsmappingservice/contactperson/ContactPersonMappingResourceIntTest.kt
This really shouldn't happen - but did when I had bad simulated data
=> SDIT-2076 Fix issue when a child has duplicate key was returning a 404

src/main/kotlin/uk/gov/justice/digital/hmpps/nomisvisitsmappingservice/contactperson/ContactPersonMappingResource.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/nomisvisitsmappingservice/contactperson/ContactPersonMappingResourceIntTest.kt
=> SDIT-2089 Fix issue where mappingType was not being returned for a duplicate contact mapping

src/main/kotlin/uk/gov/justice/digital/hmpps/nomisvisitsmappingservice/casenotes/CaseNoteMappingRepository.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/nomisvisitsmappingservice/casenotes/CaseNoteMappingService.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/nomisvisitsmappingservice/casenotes/CaseNotesMappingResource.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/nomisvisitsmappingservice/jpa/repository/NonAssociationMappingRepository.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/nomisvisitsmappingservice/casenotes/CaseNoteMappingResourceIntTest.kt
=> SDIT-2110 Handle merges for casenotes

src/main/kotlin/uk/gov/justice/digital/hmpps/nomisvisitsmappingservice/casenotes/CaseNoteMappingRepository.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/nomisvisitsmappingservice/casenotes/CaseNoteMappingService.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/nomisvisitsmappingservice/casenotes/CaseNotesMappingResource.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/nomisvisitsmappingservice/casenotes/CaseNoteMappingResourceIntTest.kt
=> SDIT-2110 Handle merges for casenotes - booking

src/main/kotlin/uk/gov/justice/digital/hmpps/nomisvisitsmappingservice/contactperson/PersonContactMappingDto.kt
Removed allowable values since this created OpenApi generated classes with duplicated enum names for some reason
=> SDIT-2090 Contact phones type enum

src/main/kotlin/uk/gov/justice/digital/hmpps/nomisvisitsmappingservice/contactperson/ContactPersonMappingResource.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/nomisvisitsmappingservice/contactperson/ContactPersonService.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/nomisvisitsmappingservice/contactperson/ContactPersonMappingResourceIntTest.kt
=> SDIT-2235 Added GET /mapping/contact-person/person/dps-contact-id/{dpssContactId}

helm_deploy/hmpps-nomis-mapping-service/Chart.yaml, src/main/resources/db/migration/V1_78__case_notes_index.sql, src/test/kotlin/uk/gov/justice/digital/hmpps/nomisvisitsmappingservice/casenotes/CaseNoteMappingResourceIntTest.kt
=> SDIT-2244 Make the casenote mapping UUID index non-unique

src/main/kotlin/uk/gov/justice/digital/hmpps/nomisvisitsmappingservice/casenotes/CaseNotesMappingResource.kt
=> SDIT-2240 Handle merges for casenotes - fix

helm_deploy/hmpps-nomis-mapping-service/Chart.yaml, helm_deploy/values-prod.yaml
=> SDIT-2339 Mapping database postgres restore schedule should be configurable

src/main/kotlin/uk/gov/justice/digital/hmpps/nomisvisitsmappingservice/corporate/CorporateMappingResource.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/nomisvisitsmappingservice/corporate/CorporateMappingResourceIntTest.kt
Added GET /corporate/migration-id/{migrationId}
=> SDIT-2420 Migration related corporate endpoints

src/main/kotlin/uk/gov/justice/digital/hmpps/nomisvisitsmappingservice/corporate/CorporateMappingDtos.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/nomisvisitsmappingservice/corporate/CorporateMappingResource.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/nomisvisitsmappingservice/corporate/CorporateService.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/nomisvisitsmappingservice/corporate/CorporateMappingResourceIntTest.kt
Also renamed endpoints that were /mapping/corporate/corporate to /mapping/corporate/organisation to avoid confusing url
Minor refactor of DTOs to cur down on duplicate code
=> SDIT-2477 Added POST /mapping/corporate/organisation

src/main/kotlin/uk/gov/justice/digital/hmpps/nomisvisitsmappingservice/corporate/AbstractCorporatePersonMapping.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/nomisvisitsmappingservice/corporate/CorporateAddressMapping.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/nomisvisitsmappingservice/corporate/CorporateAddressPhoneMapping.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/nomisvisitsmappingservice/corporate/CorporateEmailMapping.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/nomisvisitsmappingservice/corporate/CorporateMapping.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/nomisvisitsmappingservice/corporate/CorporateMappingResource.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/nomisvisitsmappingservice/corporate/CorporatePhoneMapping.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/nomisvisitsmappingservice/corporate/CorporateService.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/nomisvisitsmappingservice/corporate/CorporateWebMapping.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/nomisvisitsmappingservice/corporate/CorporateMappingResourceIntTest.kt
Minor refactor of DTOs to cut down on duplicate code
=> SDIT-2477 Added POST /mapping/corporate/address

src/main/kotlin/uk/gov/justice/digital/hmpps/nomisvisitsmappingservice/corporate/CorporateMappingDtos.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/nomisvisitsmappingservice/corporate/CorporateMappingResource.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/nomisvisitsmappingservice/corporate/CorporateService.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/nomisvisitsmappingservice/corporate/CorporateMappingResourceIntTest.kt
… 
They are all the same and causes code bloat for clients
=> SDIT-2447 Reduced all organisation domain mappings DTO to a single class

build.gradle.kts
- **SDIT-2593 Try out latest kotlin lib**
- **SDIT-2593 Upgrade to full verion of kotlin lib**
=> SDIT 2593 kotlin lib full version

src/main/kotlin/uk/gov/justice/digital/hmpps/nomisvisitsmappingservice/contactperson/ContactPersonMappingResource.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/nomisvisitsmappingservice/contactperson/ContactPersonService.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/nomisvisitsmappingservice/contactperson/PersonContactMappingDto.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/nomisvisitsmappingservice/contactperson/ContactPersonMappingResourceIntTest.kt
Need for prisoner merges where a new ste replaces the old set
=> SDIT-2374 Contact and restriction replace

src/main/kotlin/uk/gov/justice/digital/hmpps/nomisvisitsmappingservice/casenotes/CaseNoteMappingRepository.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/nomisvisitsmappingservice/casenotes/CaseNoteMappingService.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/nomisvisitsmappingservice/casenotes/CaseNotesMappingResource.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/nomisvisitsmappingservice/casenotes/CaseNoteMappingResourceIntTest.kt
Reverts ministryofjustice/hmpps-nomis-mapping-service#465
=> Revert "SDIT-2518: 🔥 Remove case notes migration"

src/main/kotlin/uk/gov/justice/digital/hmpps/nomisvisitsmappingservice/api/PublicApiResource.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/nomisvisitsmappingservice/api/PublicApiResourceIntTest.kt
Required by DPS Recall to map between CRDS and RaS
=> SDIT-2688 Sentence Public API

src/main/kotlin/uk/gov/justice/digital/hmpps/nomisvisitsmappingservice/courtsentencing/CourtSentencingMappingResource.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/nomisvisitsmappingservice/courtsentencing/CourtSentencingMappingService.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/nomisvisitsmappingservice/courtsentencing/SentenceResourceIntTest.kt
For recalls DPS will be send sync a list of DPS sentences to convert to a recall
=> SDIT-2764 batch endpoint to get all sentence mappings by dps id

src/main/kotlin/uk/gov/justice/digital/hmpps/nomisvisitsmappingservice/courtsentencing/CourtAppearanceRecallMapping.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/nomisvisitsmappingservice/courtsentencing/CourtAppearanceRecallMappingDto.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/nomisvisitsmappingservice/courtsentencing/CourtAppearanceRecallMappingRepository.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/nomisvisitsmappingservice/courtsentencing/CourtSentencingMappingResource.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/nomisvisitsmappingservice/courtsentencing/CourtSentencingMappingService.kt, src/main/resources/db/migration/V1_100__court_sentencing_court_appearance_recall.sql, src/test/kotlin/uk/gov/justice/digital/hmpps/nomisvisitsmappingservice/courtsentencing/CourtSentencingCourtAppearanceResourceIntTest.kt
* Adds ability to create the one - to - many mappings; a recall can have many court appearances 
TODO
* Add find by recallId endpoint
* Add delete by recallId endpoint
=> SDIT-2817 recall court appearance mapping

src/main/kotlin/uk/gov/justice/digital/hmpps/nomisvisitsmappingservice/contactperson/ContactPersonMappingResource.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/nomisvisitsmappingservice/contactperson/ContactPersonService.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/nomisvisitsmappingservice/contactperson/PersonContactMappingDto.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/nomisvisitsmappingservice/contactperson/PrisonerRestrictionMapping.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/nomisvisitsmappingservice/contactperson/PrisonerRestrictionMappingRepository.kt, src/main/resources/db/migration/V1_102__prisoner_restriction.sql, src/test/kotlin/uk/gov/justice/digital/hmpps/nomisvisitsmappingservice/contactperson/ContactPersonMappingResourceIntTest.kt
* Also added service/repository methods for all the other endpoints I'm about to create
=> SDIT-2899 offender restrictions PUT endpoint

src/main/kotlin/uk/gov/justice/digital/hmpps/nomisvisitsmappingservice/contactperson/ContactPersonMappingResource.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/nomisvisitsmappingservice/contactperson/ContactPersonService.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/nomisvisitsmappingservice/contactperson/ContactPersonMappingResourceIntTest.kt
Not needed for sync but as a diagnostics tool
=> SDIT-2885 Get restriction mapping for prisoner

src/main/kotlin/uk/gov/justice/digital/hmpps/nomisvisitsmappingservice/courtsentencing/CourtCaseBatchMappingDto.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/nomisvisitsmappingservice/courtsentencing/CourtSentencingMappingResource.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/nomisvisitsmappingservice/courtsentencing/CourtSentencingMappingService.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/nomisvisitsmappingservice/courtsentencing/CourtSentencingCourtCaseResourceIntTest.kt
Similar to the migration endpoint except it doesn't track a migration and will be used for a court case booking clone
=> SDIT-2982 Added court-cases/replace

src/main/kotlin/uk/gov/justice/digital/hmpps/nomisvisitsmappingservice/courtsentencing/CourtCaseBatchMappingDto.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/nomisvisitsmappingservice/courtsentencing/CourtSentencingMappingResource.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/nomisvisitsmappingservice/courtsentencing/CourtSentencingMappingService.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/nomisvisitsmappingservice/courtsentencing/CourtSentencingCourtCaseResourceIntTest.kt
Similar to the replace endpoint except the update of the mappings only requires knowledge of the from and to nomisIds not the dpsIds
=> SDIT-2982 Added court-cases/update-create
